name: Make revision
on: [push]
jobs:
  make-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Write info to version.json
        run: python3 write_version_json.py ${{ github.repository }} ${{ github.ref_name }} ${{ github.sha }}
      - name: Delete files to not include
        run: rm -rf .github *.sh write_version_json.py
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: blender_addon_updater_github_demo_HelloWorld_${{ github.sha }}
          path: ./
