name: Make revision
on: [push]
jobs:
  make-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Delete files to not include
        run: rm -rf .github *.sh
      - name: Write sha to commit.txt
        run: echo ${{ github.sha }} > commit.txt
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: fast64_${{ github.sha }}
          path: ./
